### ISSUE TITLE
MusicXML issue

### ISSUE THREAD

**Issue by githubUser01946** [0x2b3bfa0/python-blobopera#16]
`export it to [MusicXML](https://en.wikipedia.org/wiki/MusicXML).`

When I got to the MusicXML site and not the wiki linked above there is several versions of MusicXML to download.
Which one should I choose as I dont have the software it mentions after the `for`?

- Dolet® 8 Plugin for Sibelius
Saves MusicXML 4.0 files from Sibelius Ultimate 2019.5 and later, which can be opened in Finale and MakeMusic Cloud.

- Dolet® 7 Plugin for Finale
Reads and writes MusicXML 3.1 files for older 32-bit Finale versions.

- Dolet® 6 Plugin for Sibelius
Saves MusicXML 3.0 files from Sibelius 5.1 and later, which can be opened in Finale and MakeMusic Cloud.

- Dolet® 1 Plugin for Sibelius
Saves MusicXML 1.0 files from Sibelius 2.1 through 5.0, which can be opened in Finale.

**Comment by 0x2b3bfa0** [comment]
Hello, @githubUser01946! You don't need any of those plugins to save a MusicXML file; just use e.g. MuseScore to [export](https://musescore.org/en/handbook/3/opensaveexportprint#export) the score to that format.
