### ISSUE TITLE
[Feature request] Downloading result as an audio file directly

### ISSUE THREAD

**Issue by MaxGodTier** [0x2b3bfa0/python-blobopera#3]
After I upload a recording to the server, I get a link to listen to the results from a web browser, however, is there any efficient way to programmatically download the results as an audio file (ie. wav, mp3)? That would be a neat feature to integrate in your repo.

**Comment by 0x2b3bfa0** [comment]
@MaxGodTier, unfortunately that's not easy at all.

Blob Opera renders audio on the browser with [WebAssembly](https://webassembly.org/) and a couple of trained models. Extracting the audio locally would require either implementing the synthesis code in pure Python or emulating the original application with [Selenium](https://www.selenium.dev/) or something similar. None of these approaches seem easy to implement and I would like to avoid adding that layer of complexity to this project, but you can try to record the audio from your web browser with [an extension](https://chrome.google.com/webstore/detail/chrome-audio-capture/kfokdmfpdnokpmpbjhjbcabgligoelgp) as a workaround.

**Comment by 0x2b3bfa0** [comment]
Feel free to reopen this issue if you're willing to implement this feature with any of the suggested _hard_ methods. Reimplementing all the code would be really fun, but would also require insane amounts of effort and time.
