### ISSUE TITLE
How to have consonnants at the end of a note before a rest?

### ISSUE THREAD

**Issue by tnodet** [0x2b3bfa0/python-blobopera#5]
Hi,

First and foremost, I want to say that this is a fantastic library, very well written and works like a charm! Thank you @0x2b3bfa0 ☺

I've had a lot of fun playing with it for the last couple days, but I've hit some kind of issue:
**When I have a note with lyrics ending with a consonnant, followed by a rest, the blobs won't produce the sound of the consonnant.**
It is especially true for some phonemes like `S` and `Z`.

Here is an example, with the song _And So It Goes_ from Billy Joel, arranged by Bob Chilcott: [https://g.co/arts/E6CEX4ruF83QyjyU6](https://g.co/arts/E6CEX4ruF83QyjyU6).
In the second verse, the sentences end with the words "tones" (phonemes: `tonz`), "pretense" (`pritens`), "much" (`match`) and "defense" (`difens`).
Each word is followed by a rest (wich translates to silence phonemes).
None of those ending consonnants are pronounced by the blobs.

It seems to me like this is a limitation of Blob Opera itself, but I'm curious to see if there are workarounds.

Things I've tried:
* **removing the rests** (by prolonging the note at the end of each sentence up to the starting note of the next sentence): it works, but of course not for the last sentence. It also changes the song quite a lot.
* **doubling the consonnant / adding another consonnant** before or after: it doesn't seem to do anything, at least not with the consonnants I've tried
* **replace the start of the rest with a very short vowel note**: even with 64th or 128th notes, the blobs will sing a longer vowel (maybe equivalent to an 8th or a 16th), so the result is quite poor.

Is this something you have encountered? If so, any tips?😄

**Comment by 0x2b3bfa0** [comment]
👋  Hi, @tnodet! 😊 

```console
blobopera recording download https://g.co/arts/E6CEX4ruF83QyjyU6 recording.bin
blobopera recording export recording.bin recording.musicxml
```

<details><summary>Click to reveal the score fragments...</summary>

![Captura de pantalla 2021-04-30 a las 20 45 27](https://user-images.githubusercontent.com/11387611/116740330-2c491200-a9f5-11eb-9621-b17ffef18ff0.png)
![Captura de pantalla 2021-04-30 a las 20 45 46](https://user-images.githubusercontent.com/11387611/116740334-2e12d580-a9f5-11eb-9772-8a7103de9b5e.png)
![Captura de pantalla 2021-04-30 a las 20 46 06](https://user-images.githubusercontent.com/11387611/116740342-30752f80-a9f5-11eb-8e28-f0ce3b775aca.png)

</details>

**Comment by 0x2b3bfa0** [comment]
👋  Hi, @tnodet!

As far as I know, this is a Blob Opera limitation. The only workaround I can think of right now would be using _tosh_,  _pritesh_, _mash_ and _difesh_, ending with any [`vowel`](https://0x2b3bfa0.github.io/python-blobopera/blobopera.phoneme.html#blobopera.phoneme.Phoneme.is_vowel) immediately followed by the [`sh`](https://0x2b3bfa0.github.io/python-blobopera/blobopera.phoneme.html#blobopera.phoneme.Phoneme.SH) consonant, so the two rightmost blobs (tenor and bass) can utter the final [_`ʃ`_](https://en.wikipedia.org/wiki/Voiceless_postalveolar_fricative) sound.

You can preview the result [here](https://g.co/arts/nhraLM2aTjRBzWtf8) and run the following commands to inspect its MusicXML representation:
```console
blobopera recording download https://g.co/arts/nhraLM2aTjRBzWtf8 recording.bin
blobopera recording export recording.bin recording.musicxml
```

I'm really happy to find that this project has been useful for somebody else. 😊

**Comment by 0x2b3bfa0** [comment]
Closing after a month of inactivity; feel free to reopen.
