### ISSUE TITLE
Not an issue. Just a suggestion to have the default of `blob opera import --fill` to be A or U instead of silence

### ISSUE THREAD

**Issue by LKchemposer** [0x2b3bfa0/python-blobopera#6]
The code works GREAT! But it took me quite a bit of time to figure out the --fill because I tested it first with a score without lyrics, and the recording doesn't have any sound. Again, this is not a huge issue, but a minor suggestion. All in all, really awesome stuff!

**Comment by 0x2b3bfa0** [comment]
Fixed with db62c946075360ee03cf2eddcc1d576358c79995! Thank you very much!
