### ISSUE TITLE
New recording: Ave Verum Corpus

### ISSUE THREAD

**Issue by LKchemposer** [0x2b3bfa0/python-blobopera#7]
* **Name of the original music: Ave Verum Corpus KV 618**
* **Author of the original music: Wolfgang Amadeus Mozart**
* **Link to the original score: http://www.cafe-puccini.dk/Mozart/pdf/Ave_verum_corpus.pdf**
* **Link to the recording: https://g.co/arts/FqjgC2WJ6HyC2otv9**

**Comment by 0x2b3bfa0** [comment]
Thank you very much, @LKchemposer! 🙏🏼  I used to sing [KV 618](https://en.wikipedia.org/wiki/Ave_verum_corpus_(Mozart)) after [KV 317](https://en.wikipedia.org/wiki/Coronation_Mass_(Mozart)) before the pandemic, as part of [a small concert choir](http://www.cuencaciudadmusica.es/portal/rowid__1015527,63602/tabid__26311/Default.aspx).
